#! ---------------------------------------------------------------
#! Aurora Theme for Hexo
#! ---------------------------------------------------------------
#! Designed & Coded By TriDiamond
#! ---------------------------------------------------------------

#! ---------------------------------------------------------------
#! Site Configs
#！ @docs https://aurora.tridiamond.tech/guide/configuration.html
#! ---------------------------------------------------------------
site:
  subtitle: Telos
  author: LDxiaodi
  nick: 'Telos / 利马计划·档案室'
  description: '这里是利马计划档案室。<br/>存储着设定和档案的最高知识库。'
  link: '/'
  language: cn
  multi_language: true
  logo: /images/telos.jpg
  avatar: /images/ldxiaodi.jpg
  beian:
    number: ''
    link: ''
  police_beian:
    number: ''
    link: ''

#! ---------------------------------------------------------------
#! Authors Configs
#！ @docs https://aurora.tridiamond.tech/guide/authors.html
#! ---------------------------------------------------------------
authors:
  ##! example
  # TriDiamond:
  #   name: TriDiamond
  #   avatar: https://up.enterdesk.com/edpic_source/44/ff/3d/44ff3d6bd2819d524facfcc33205d4cd.jpg
  #   link: https://github.com/TriDiamond
  #   description: 'Think like an artist, code like an artisan.'
  #   socials:
  #     github: https://tridiamond.tech

#! ---------------------------------------------------------------
#! Menu Configs
#！ @docs https://aurora.tridiamond.tech/guide/menu.html
#! ---------------------------------------------------------------
menu:
  About: true
  Tags: true
  Archives: true

#! ---------------------------------------------------------------
#! Theme Config
#! @docs https://aurora.tridiamond.tech/guide/theme.html
#! ---------------------------------------------------------------
theme:
  dark_mode: true
  profile_shape: circle # support `circle`, `diamond`, `rounded`
  feature: true
  gradient:
    color_1: '#24c6dc'
    color_2: '#5433ff'
    color_3: '#ff0099'

#! ---------------------------------------------------------------
#! Social Configs
#! @docs https://aurora.tridiamond.tech/guide/social.html
#! ---------------------------------------------------------------
socials:
  customs:
  ##! Example:
  ##! --- Using SVG
  # bilibili:
  #   icon: http://localhost:4000/svg/bilibili.svg
  #   link: https://live.bilibili.com/22619211

  ##! --- Using IconFont
  # baidu:
  #   icon: iconfont icon-baidu
  #   link: https://live.bilibili.com/22619211

  ##! --- Using FontAwesome
  # book:
  #   icon: far fa-address-book
  #   link: https://live.bilibili.com/22619211

#! ---------------------------------------------------------------
#! Site Meta Configs
#! @docs https://aurora.tridiamond.tech/guide/theme.html
#! ---------------------------------------------------------------
site_meta:
  cdn: cn
  favicon:
  description: ''
  keywords: ''
  author: ''

#! ---------------------------------------------------------------
#! Plugins
#! @docs https://aurora.tridiamond.tech/guide/plugins.html
#! ---------------------------------------------------------------

# For local development only!
gitalk:
  enable: true
  autoExpand: true
  clientID: ''
  clientSecret: ''
  repo: 'dev-blog-comments'
  owner: 'TriDiamond'
  admin: ['TriDiamond']
  id: uid
  language: en
  distractionFreeMode: true
  recentComment: true
  proxy: ''

# Valine comment plugin (recommended!)
# see https://valine.js.org/quickstart.html
valine:
  enable: false
  app_id:
  app_key:
  avatar: ''
  placeholder: Leave your thoughts behind~
  visitor: true
  lang: en
  avatarForce: false
  meta: ['nick', 'mail']
  requiredFields: []
  admin: 'TriDiamond'
  recentComment: true

# Enable Busuanzi statistic plugin
# see http://ibruce.info/2015/04/04/busuanzi/
busuanzi:
  enable: true

copy_protection:
  enable: true
  author:
    cn: 作者
    en: Author
  link:
    cn: 本文来自于
    en: Article is from
  license:
    cn: 博客内容遵循 CC BY-NC-ND 协议
    en: This content is shared under the CC BY-NC-ND

#! ---------------------------------------------------------------
#! Enable Aurora Bot Dia
#! @docs https://aurora.tridiamond.tech/guide/site-meta.html#custom-meta
#! ---------------------------------------------------------------
aurora_bot:
  enable: true
  locale: cn
  bot_type: dia
  tips:
    # ======================================================
    # 这些是 Dia 每30秒会说的随机消息。
    # ======================================================
    messages:
      - 你好，我是 <span>Juzi</span>，基于Dia外观为「利马计划云端档案库」定制的助理。
      - 好久不见，工作进行的怎么样了?
      - '<span>你好...</span>执棋者多久没有浏览档案了?'
      - 嗯?
      - 嗷QWQ
      - 执棋者很专注呢，请记得及时休息。
      - 你可以<span>点击我</span>返回页面顶部。
      # 这是一个特殊的函数，它将触发 quotes API
      # 和 Dia 会说出每日引用的信息。
      - showQuote

    # ======================================================
    # 将在用户打开浏览器控制台时触发。
    # ======================================================
    console: 检测到你打开了控制台，没什么好看的...嗯。

    # ======================================================
    # 当用户从你的博客上复制内容时触发。
    # ======================================================
    copy: 复制了些什么？转载请记得加上出处。

    # ======================================================
    # 这将在用户返回窗口时触发。
    # ======================================================
    visibility_change: 欢迎回来。

    # ======================================================
    # 欢迎留言，号码是一天中的时间。
    # -----------------------------------
    # eg: 24 = 00:00 也就是午夜
    # eg: 17-19 = 在下午 5 点到 7 点之间
    # -----------------------------------
    # 在一天的这段时间里，Dia 会向你的读者问好
    # 与相应的消息。
    # ======================================================
    welcome:
      '24': 执棋者，夜深了，在为Telos做出贡献的同时，请不要忽视您的健康。
      '5_7': 早上好执棋者。一日之计在于晨，美好的一天就要开始了。
      '7_11': 上午好执棋者。工作顺利嘛，不要久坐，请多起来走动走动。
      '11_13': 中午了，工作了一个上午，现在是午餐时间。
      '13_17': 午后很容易犯困呢，今天的档案完成了吗？
      '17_19': 这是傍晚时分。窗外夕阳的景色在您勤奋的身影下显得格外美丽。
      '19_21': 晚上好，愿至高神与你同在。
      '21_23':
        - 已经这么晚了呀，早点休息吧，愿至高神与你同在
        - 深夜时请爱护眼睛。

    # ======================================================
    # 当用户来自搜索引擎时使用。
    # ======================================================
    referrer:
      # 用户来自你自己的网站。
      self: 欢迎来到<span>「利马计划云端档案库」</span>
      # 用户来自百度搜索引擎。
      baidu: Hello！来自 百度搜索 的朋友<br>你是搜索 <span>「[PLACEHOLDER]」</span> 找到的我吗？
      # 用户来自360搜索引擎。
      so: Hello！来自 360搜索 的朋友<br>你是搜索 <span>「[PLACEHOLDER]」</span> 找到的我吗？
      # 用户来自谷歌搜索引擎。
      google: Hello！来自 谷歌搜索 的朋友<br>欢迎阅读<span>「[PLACEHOLDER]」</span>
      # 用户来自另一个网站。
      site: Hello！来自 <span>「异世奇缘」</span> 的朋友
      # 任何其他来源。
      other: 感谢您浏览： <span>「利马计划云端档案库」</span>

    # ======================================================
    # 当你的'鼠标悬停'到特定的HTML标签，Dia将
    # 给用户留言帮助他们解决问题。
    # ------------------------------------------------------
    # selector: 标签选择器(你可以使用任何css选择器)
    # text: 这是Dia将要传达的信息。(如果你想要的
    #       Dia从一组信息中随机说出一个，设置它
    #       数组，否则只是纯文本)
    #  ======================================================
    mouseover:
      # 悬浮在 Dia 上
      - selector: '#Aurora-Dia'
        text:
          - 欸哆... <span>你想干嘛</span>?
          - 请集中注意在您的查阅上...时不时逗逗我其实也可以。
          - '<span>执棋者，我在。</span> 有什么可以帮到你? '
      # 悬浮在 Home 菜单
      - selector: "[data-menu='Home']"
        text:
          - 点击前往首页，回到上一页请使用浏览器的后退功能。
          - 点击回到首页。
          - 回首页看看吧。
      # 悬浮在 About 菜单
      - selector: "[data-menu='About']"
        text:
          - 你想知道我家主人是谁吗？
          - 这里有一些关于我家主人的秘密哦，要不要看看呢？
          - 发现主人出没地点！
      # 悬浮在 Archives 菜单
      - selector: "[data-menu='Archives']"
        text:
          - 这里存储了所有的档案。
          - 请尽情阅览~
      # 悬浮在 Tags 菜单
      - selector: "[data-menu='Tags']"
        text:
          - 点击查看文章的标签。
          - 使用标签可以更好的分类你的文章。
      # 悬浮在 language 菜单
      - selector: "[data-dia='language']"
        text: 「利马计划云端档案库」支持多种语言。
      # 悬浮在黑白切换按钮上
      - selector: "[data-dia='light-switch']"
        text: 您可以点击这里切换黑白模式。
      # 悬浮在作者简介上
      - selector: "[data-dia='author']"
        text:
          - 这是「利马计划云端档案库」的简介。
          - 点击其中任何一个链接都可以传送到「利马计划云端档案库」的其他世界。
      # 悬浮在作跳转评论按钮上
      - selector: "[data-dia='jump-to-comment']"
        text:
          - 你想看看评论吗?
          - 点击这里可以帮助你直接跳转到评论部分。

    # ======================================================
    # 当你的'鼠标点击'为特定的HTML标签，Dia将
    # 给用户留言帮助他们解决问题。
    # ------------------------------------------------------
    # 属性与' moveover '事件相同
    # ======================================================
    click:
      # 鼠标点击搜索按钮
      - selector: "[data-dia='search']"
        text:
          - 键入关键词以查询需要的文档。
          - 你可以使用 ctrl/cmd + k 快捷键打开搜索。
      # 鼠标点击文章标题
      - selector: "[data-dia='article-link']"
        text:
          - 你正在浏览：<span>「{text}」</span>.
          - 您的选择真的不错哦！好好享受这篇文章吧～
          - 希望你能从 <span>「{text}」</span>这篇文章中得到些许灵感。
      # 鼠标点击跳转评论输入框（Gitalk）
      - selector: '.gt-header-textarea'
        text:
          - 执棋者有什么话要说吗？
          - 填写请三思。
          - 欸哆...请友善一些。
          - 如果有更多的问题，可以向LDxiaodi寻求帮助。
      # 鼠标点击跳转评论输入框（Valine）
      - selector: '.veditor'
        text:
          - 执棋者有什么话要说吗？
          - 填写请三思。
          - 欸哆...请友善一些。
          - 如果有更多的问题，可以向LDxiaodi寻求帮助。

    # ======================================================
    # 在特定的日期，Dia会向你的读者问候。
    # ------------------------------------------------------
    # date: 特别活动的日期(格式:月/日或月/日-月/日)
    # text:
    # ---只使用一个简单的字符串。
    # -——消息的随机集合，使用数组配置格式。
    # ======================================================
    events:
      - date: 01/01
        text: '<span>元旦</span>了，新的一年又开始了。'
      - date: 02/14
        text: 又是一年<span>情人节</span>啊...嗯?看着我干嘛?
      - date: 03/08
        text: 今天是<span>国际妇女节</span>！
      - date: 03/12
        text: 今天是<span>植树节</span>，请保护环境！
      - date: 04/01
        text: 悄悄告诉你一个秘密：<span>今天是愚人节...不要被骗了</span>
      - date: 05/01
        text: 今天是<span>五一劳动节</span>，计划好假期去哪里了吗?
      - date: 06/01
        text: '<span>儿童节</span>了呢，快活的时光总是短暂，要是永远长不大该多好啊...咳'
      - date: '09/03'
        text: '<span>中国人民抗日战争胜利纪念日</span>，铭记历史、缅怀先烈、珍爱和平、开创未来。'
      - date: '09/10'
        text: '<span>教师节</span>，在学校要给老师问声好呀！'
      - date: 10/01
        text: '<span>国庆节</span>到了，为祖国母亲庆生！'
      - date: 11/05-11/12
        text: 今年的<span>双十一</span>是和谁一起过的呢...作业?
      - date: 12/20-12/31
        text: 这几天是<span>圣诞节</span>，注意保暖。

#! ---------------------------------------------------------------
#! Injections
#! @docs https://aurora.tridiamond.tech/guide/site-meta.html#custom-meta
#! ---------------------------------------------------------------
injects:
  scripts:
  css:
